# 1.create a 3x3x3 array with random values.

In [3]:
import numpy as np
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.80625051 0.69142097 0.77594157]
  [0.70942077 0.77730167 0.4272862 ]
  [0.22025869 0.79108056 0.23224013]]

 [[0.20381146 0.62422813 0.48118967]
  [0.19459413 0.74434322 0.36993047]
  [0.5287267  0.85273725 0.82610713]]

 [[0.99835516 0.87388642 0.96983177]
  [0.27712065 0.68213192 0.2916535 ]
  [0.16982425 0.914502   0.07554566]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [4]:
import numpy as np

matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3. create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [6]:
import numpy as np

# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

min_val = np.min(random_matrix)
max_val = np.max(random_matrix)

# Normalizing the matrix
normalized_matrix = (random_matrix - min_val) / (max_val - min_val)

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[0.16145193 0.54000234 0.99259023 0.4751466  0.66339014]
 [0.57089782 0.66645106 0.926538   0.71892742 0.42156741]
 [0.83075664 0.15157122 0.51277586 0.3630217  0.22122797]
 [0.12418229 0.46278275 0.70649099 0.92520808 0.35037999]
 [0.51083315 0.77687437 0.85007629 0.53915394 0.45715805]]

Normalized Matrix:
[[0.04291721 0.47883032 1.         0.40414683 0.62091538]
 [0.51440747 0.62444014 0.92393871 0.68486837 0.34244864]
 [0.81364336 0.03153925 0.44747814 0.27503136 0.11175126]
 [0.         0.38990945 0.67054742 0.92240727 0.26047401]
 [0.44524104 0.75159617 0.83589056 0.47785336 0.38343243]]


# 5. How to find common values between two arrays?

In [9]:
import numpy as np
s
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 1])

common_values = np.intersect1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)
print("Common Values:", common_values)


Array1: [1 2 3 4 5]
Array2: [6 7 8 9 1]
Common Values: [1]


# 6.How to get the dates of yesterday, today and tomorrow?

In [36]:
import numpy as np
from datetime import datetime, timedelta

# Get the current date
current_date = datetime.now()

current_date_np = np.datetime64(current_date)

# Calculate yesterday and tomorrow
yesterday_np = current_date_np - np.timedelta64(1, 'D')
tomorrow_np = current_date_np + np.timedelta64(1, 'D')

yesterday = yesterday_np.item()
today = current_date_np.item()
tomorrow = tomorrow_np.item()

yesterday_str = yesterday.strftime("%d-%m-%Y")
today_str = today.strftime("%d-%m-%Y")
tomorrow_str = tomorrow.strftime("%d-%m-%Y")

# Print the dates
print("Yesterday's date:", yesterday_str)
print("Today's date:", today_str)
print("Tomorrow's date:", tomorrow_str)


Yesterday's date: 20-09-2023
Today's date: 21-09-2023
Tomorrow's date: 22-09-2023


# 7. Consider two random array A and B , check if they are equal.

In [37]:
import numpy as np

A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("The two Arrays A and B are not equal.")


The two Arrays A and B are not equal.


# 8. Create a random vector of size 10 and replace the maximum value by 0

In [38]:
import numpy as np

random_vector = np.random.rand(10)

# Finding the index of the maximum value
max_index = np.argmax(random_vector)

random_vector[max_index] = 0

print("Original Vector:", random_vector)


Original Vector: [0.03643512 0.54404567 0.82020608 0.51929926 0.09967874 0.
 0.83026205 0.78913678 0.52251069 0.25031672]


# 9. How to print all the values of an array?

In [16]:
import numpy as np

my_array = np.array([11, 22, 43, 34, 95])
print(my_array)


[11 22 43 34 95]


# 10. Subtract the mean of each row of a matrix

In [39]:
import numpy as np

# Create a sample matrix (2x3 in this case)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1)

# Subtract the row means from the matrix
result_matrix = matrix - row_means.reshape(-1, 1)

print("Original Matrix:")
print(matrix)

print("\nRow Means:")
print(row_means)

print("\nRow Means Subtracted Matrix:")
print(result_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]]

Row Means:
[2. 5.]

Row Means Subtracted Matrix:
[[-1.  0.  1.]
 [-1.  0.  1.]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector

In [40]:
import numpy as np

# Given vector
given_vector = np.array([10, 20, 30, 40, 50])

# Second vector containing indices
indices_vector = np.array([1, 2, 3, 2, 4])

# Create an array to store the results
result_vector = np.copy(given_vector)

# Add 1 to elements indexed by the second vector
result_vector[indices_vector] += 1

print("Given Vector:")
print(given_vector)

print("\nIndices Vector:")
print(indices_vector)

print("\nResultant Vector:")
print(result_vector)


Given Vector:
[10 20 30 40 50]

Indices Vector:
[1 2 3 2 4]

Resultant Vector:
[10 21 31 41 51]


# 12. How to get the diagonal of a dot product?

In [19]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Compute the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal of the dot product using np.diag()
diagonal = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array?

In [24]:
import numpy as np

# Create an example array
arr = np.array([2, 3, 2, 5, 6, 5, 2, 3, 4, 5, 5, 6, 2, 5])

# Use numpy.bincount() to count occurrences of each element
counts = np.bincount(arr)

# Use numpy.argmax() to find the index with the maximum count
most_frequent_value = np.argmax(counts)

print("Original Array:")
print(arr)

print("\nMost Frequent Value is:", most_frequent_value)


Original Array:
[2 3 2 5 6 5 2 3 4 5 5 6 2 5]

Most Frequent Value: 5


# 14. How to get the n largest values of an array 

In [26]:
import numpy as np

# Create an example array
arr = np.array([5, 12, 9, 1, 3, 15, 7, 8, 10])

# Specify the value of n (number of largest values to retrieve)
n = 5

# Use numpy.partition() to partition the array
partitioned = np.partition(arr, -n)

# Get the n largest values from the partitioned array
n_largest_values = partitioned[-n:]

print("Original Array:")
print(arr)

print("\n{} Largest Values are:".format(n))
print(n_largest_values)


Original Array:
[ 5 12  9  1  3 15  7  8 10]

5 Largest Values:
[ 8  9 10 12 15]


# 15.How to create a record array from a regular array?

In [30]:
import numpy as np

# Create a regular array
regular_array = np.array([("Anu", 24, 8.5),
                          ("Abi", 23, 7.0),
                          ("Aruna", 22, 9.2)],
                         dtype=[('name', 'U10'), ('age', int), ('gpa', float)])

# Create a record array from the regular array
record_array = np.core.records.fromarrays(regular_array.T, names="name,age,gpa")

# Access data in the record array
print("Record Array:")
print(record_array)

# Access individual fields
print("\nNames:")
print(record_array["name"])

print("\nAges:")
print(record_array["age"])

print("\nGPAs:")
print(record_array["gpa"])


Record Array:
(('Anu', 24, 8.5), ('Abi', 23, 7.), ('Aruna', 22, 9.2))

Names:
('Anu', 24, 8.5)

Ages:
('Abi', 23, 7.)

GPAs:
('Aruna', 22, 9.2)


# 16. How to swap two rows of an array?

In [32]:
import numpy as np

# Create an example 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swap rows 1 and 2 (0-based indexing)
row1, row2 = 1, 2
arr[[row1, row2]] = arr[[row2, row1]]

print("Original Array:")
print(arr)


Original Array:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


# 17. Write a python code to reshape to next dimension of numpy array?

In [33]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array to a 2D array
arr2d = arr1d.reshape(-1, 2)

print("Original 1D Array:")
print(arr1d)

print("\nReshaped 2D Array:")
print(arr2d)


Original 1D Array:
[1 2 3 4 5 6]

Reshaped 2D Array:
[[1 2]
 [3 4]
 [5 6]]
